# Generated by Django 5.1.1 on 2024-09-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagory',
            new_name='category',
        ),
    ]
